//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomStuff
{
    [Serializable]
    public class UnitySailTwistMsg : Message
    {
        public const string k_RosMessageName = "custom_stuff/UnitySailTwist";
        public override string RosMessageName => k_RosMessageName;

        public int twist;

        public UnitySailTwistMsg()
        {
            this.twist = 0;
        }

        public UnitySailTwistMsg(int twist)
        {
            this.twist = twist;
        }

        public static UnitySailTwistMsg Deserialize(MessageDeserializer deserializer) => new UnitySailTwistMsg(deserializer);

        private UnitySailTwistMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.twist);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.twist);
        }

        public override string ToString()
        {
            return "UnitySailTwistMsg: " +
            "\ntwist: " + twist.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
